# Generated by Django 3.2.16 on 2024-05-15 08:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240515_1205'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
